---
title: "MN_Covid_Map"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


library(tidyverse)
library(leaflet)
library(rgdal)

```

## County Maps


```{r cars}

counties <- readOGR("C:/Users/nick/OneDrive/Documents/GitHub/MN_Covid_Map/shpmn2")
counties$ALAND <- as.numeric(as.character(counties$ALAND))

states <- readOGR("C:/Users/nick/OneDrive/Documents/GitHub/MN_Covid_Map/shp")
states$ALAND <- as.numeric(as.character(states$ALAND))

```



```{r}

neStates <- subset(states, states$STUSPS %in% c(
  "CT","ME","MA","NH","RI","VT","NY","NJ","PA"
))

leaflet(neStates) %>%
  addPolygons(color = "#444444", weight = 1, smoothFactor = 0.5,
    opacity = 1.0, fillOpacity = 0.5,
    fillColor = ~colorQuantile("YlOrRd", ALAND)(ALAND),
    highlightOptions = highlightOptions(color = "white", weight = 2,
      bringToFront = TRUE))

```



```{r}

neStates <- subset(states, states$STUSPS %in% c(
  "CT","ME","MA","NH","RI","VT","NY","NJ","PA"
))

leaflet(states) %>%
  addPolygons(color = "#444444", weight = 1, smoothFactor = 0.5,
    opacity = 1.0, fillOpacity = 0.5,
    fillColor = ~colorQuantile("YlOrRd", ALAND)(ALAND),
    highlightOptions = highlightOptions(color = "white", weight = 2,
      bringToFront = TRUE))

```




```{r}

MNshap <- subset(counties, counties$STATEFP %in% c(27))

MNshap$NAME<- as.character(MNshap$NAME)
MNshap$NAME<- factor(MNshap$NAME)

MNshap$colorcoat <- rnorm(length(MNshap$NAME),  mean = 25, sd = 10)

leaflet(MNshap) %>%
  addPolygons(color = "#444444", weight = 1, smoothFactor = 0.5,
    opacity = 1.0, fillOpacity = 0.5,
    fillColor = ~colorQuantile("YlOrRd", colorcoat)(colorcoat),
    highlightOptions = highlightOptions(color = "white", weight = 2,
      bringToFront = TRUE))

```

